steps:
# Step 1: Publish the application
- name: 'mcr.microsoft.com/dotnet/sdk:8.0'
  entrypoint: 'dotnet'
  args: ['publish', '--configuration', 'Release', '--output', 'HelloWorld']

# Step 2 Install ZIP package
- name: 'alpine'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      apk add --no-cache zip &&
      zip -r HelloWorld.zip HelloWorld/*
      
# Step 3: Copy the artifacts to the Google Cloud Storage bucket
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', '-r', 'HelloWorld.zip', 'gs://dotnetcore8app-artifacts/artifacts/']

artifacts:
  objects:
    location: 'gs://dotnetcore8app-artifacts/artifacts/'
    paths: ['HelloWorld.zip']
options:
  logging: CLOUD_LOGGING_ONLY
  logging: CLOUD_LOGGING_ONLY
timeout: '1200s'  # Optional: Customize the timeout if needed